services:
  categorizer-api:
    image: 172.16.240.5:5000/ticket-categorizer-api:latest
    ports:
      - 8080:8000
    env_file:
      - .env
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]